export const PETS = [
  { id: 'white-cat', name: '白猫', folder: '白猫十阶段图片' },
  { id: 'bichon', name: '比熊', folder: '比熊十阶段图片' },
  { id: 'border-collie', name: '边牧', folder: '边牧十阶段图片' },
  { id: 'ragdoll', name: '布偶', folder: '布偶十阶段图片' },
  { id: 'shiba', name: '柴犬', folder: '柴犬十阶段图片' },
  { id: 'french-bulldog', name: '法斗', folder: '法斗十阶段图片' },
  { id: 'black-cat', name: '黑猫', folder: '黑猫十阶段图片' },
  { id: 'tabby', name: '虎斑', folder: '虎斑十阶段图片' },
  { id: 'garfield', name: '加菲猫', folder: '加菲猫十阶段图片' },
  { id: 'golden-shaded', name: '金渐层', folder: '金渐层十阶段图片' },
  { id: 'golden-retriever', name: '金毛', folder: '金毛十阶段图片' },
  { id: 'orange-cat', name: '橘猫', folder: '橘猫十阶段图片' },
  { id: 'corgi', name: '柯基', folder: '柯基十阶段图片' },
  { id: 'labrador', name: '拉布拉多', folder: '拉布拉多十阶段图片' },
  { id: 'blue-cat', name: '蓝猫', folder: '蓝猫十阶段图片' },
  { id: 'samoyed', name: '萨摩耶', folder: '萨摩耶十阶段图片' },
  { id: 'calico', name: '三花', folder: '三花十阶段图片' },
  { id: 'teddy', name: '泰迪', folder: '泰迪十阶段图片' },
  { id: 'siamese', name: '暹罗猫', folder: '暹罗猫十阶段图片' },
  { id: 'silver-shaded', name: '银渐层', folder: '银渐层十阶段图片' },
  { id: 'rabbit', name: '小兔子', folder: '小兔子十阶段图片' },
  { id: 'squirrel', name: '松鼠', folder: '松鼠十阶段图片' },
  { id: 'panda', name: '熊猫', folder: '熊猫十阶段图片' },
  { id: 'turtle', name: '乌龟', folder: '乌龟十阶段图片' },
  { id: 'hamster', name: '仓鼠', folder: '仓鼠十阶段图片' },
  { id: 'polar-bear', name: '大白熊', folder: '大白熊十阶段图片' },
  { id: 'monkey', name: '猴子', folder: '猴子十阶段图片' },
  { id: 'duck', name: '鸭子', folder: '鸭子十阶段图片' },
  { id: 'lihua-cat', name: '狸花猫', folder: '狸花猫十阶段图片' },
  { id: 'nine-tailed-fox', name: '九尾狐', folder: '九尾狐十阶段图片' },
  { id: 'capybara', name: '卡皮巴拉', folder: '卡皮巴拉十阶段图片' },
  { id: 'schnauzer', name: '雪瑞纳', folder: '雪瑞纳十阶段图片' },
  { id: 'chinese-rural-dog', name: '中华田园犬', folder: '中华田园犬十阶段图片' },
  { id: 'chihuahua', name: '吉娃娃', folder: '吉娃娃十阶段图片' },
  { id: 'westie', name: '西高地', folder: '西高地十阶段图片' },
  { id: 'lamb', name: '小羊羔', folder: '小羊羔十阶段图片' },
  { id: 'tiger', name: '老虎', folder: '老虎十阶段图片' },
  { id: 'leopard', name: '豹子', folder: '豹子十阶段图片' },
  { id: 'dinosaur', name: '恐龙', folder: '恐龙十阶段图片' },
  { id: 'chick', name: '小黄鸡', folder: '小黄鸡十阶段图片' },
  { id: 'parrot', name: '鹦鹉', folder: '鹦鹉十阶段图片' },
  { id: 'fox', name: '狐狸', folder: '狐狸十阶段图片' },
  { id: 'frog', name: '青蛙', folder: '青蛙十阶段图片' },
  { id: 'crocodile', name: '鳄鱼', folder: '鳄鱼十阶段图片' },
  { id: 'elephant', name: '大象', folder: '大象十阶段图片' },
  { id: 'sika-deer', name: '梅花鹿', folder: '梅花鹿十阶段图片' },
  { id: 'chameleon', name: '变色龙', folder: '变色龙十阶段图片' },
  { id: 'raccoon', name: '小浣熊', folder: '小浣熊十阶段图片' },
  { id: 'koala', name: '考拉', folder: '考拉十阶段图片' },
  { id: 'otter', name: '水獭', folder: '水獭十阶段图片' },
  { id: 'chinchilla', name: '龙猫', folder: '龙猫十阶段图片' },
  { id: 'unicorn', name: '独角兽', folder: '独角兽十阶段图片' },
  { id: 'husky', name: '哈士奇', folder: '哈士奇十阶段图片' },
  { id: 'guinea-pig', name: '荷兰猪', folder: '荷兰猪十阶段图片' },
  { id: 'lion-cub', name: '小狮子', folder: '小狮子十阶段图片' },
  { id: 'whale', name: '小鲸鱼', folder: '小鲸鱼十阶段图片' },
  { id: 'dolphin', name: '海豚', folder: '海豚十阶段图片' },
  { id: 'hedgehog', name: '小刺猬', folder: '小刺猬十阶段图片' },
  { id: 'chipmunk', name: '花栗鼠', folder: '花栗鼠十阶段图片' },
  { id: 'flamingo', name: '火烈鸟', folder: '火烈鸟十阶段图片' },
  { id: 'red-panda', name: '小熊猫', folder: '小熊猫十阶段图片' },
  { id: 'baby-shark', name: '小鲨鱼', folder: '小鲨鱼十阶段图片' }
]

export const getPetImageUrl = (folder, stage) => {
  const baseUrl = import.meta.env.VITE_IMAGE_BASE_URL || '/pet-images'
  // 显式转义中文路径，防止部分浏览器或代理出现连接异常
  const encodedFolder = encodeURIComponent(folder)
  return `${baseUrl}/${encodedFolder}/${stage}.webp`
}
